language: php

php:
  - 5.3
#  - 5.4
#  - 5.5
#  - 5.6
#  - hhvm

matrix:
  allow_failures:
    - php: hhvm

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite

before_script:
  - composer self-update
  - composer install --no-progress
  - phpenv rehash
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart

  - chmod 777 system/cms/config
  - chmod -R 777 system/cms/cache
  - chmod -R 777 addons
  - chmod -R 777 assets/cache
  - chmod -R 777 uploads
  - chmod 777 system/cms/modules/streams_core/models

  # MySQL specific
  - mysql -e 'create database pyrocms;'

  # PostgreSQL specific
  - psql -c 'create database pyrocms;' -U postgres; fi"
  - export PYRO_DB_USER=postgres; fi"
  - export PYRO_DB_DRIVER=pgsql; fi"

  # SQLite specific
  - touch build/test.sqlite
  - chmod 666 build/test.sqlite

  # Generic DB Settings
  - export PYRO_DB_HOST=127.0.0.1
  - export PYRO_WEB_HOST=127.0.0.1

script:
  - PYRO_DB_DRIVER=sqlite ./system/vendor/bin/phing integration-test
  - PYRO_DB_DRIVER=mysql PYRO_DB_USER=travis ./system/vendor/bin/phing integration-test
  - PYRO_DB_DRIVER=pgsql PYRO_DB_USER=postgres ./system/vendor/bin/phing integration-test

branches:
  exclude:
    - 2.0/master
    - 2.1/develop
    - 2.1/master
